name: Lint

on:
  push:
    branches:
      - main
    paths:
      - "bin/*"
      - ".github/workflows/*"
  pull_request:
    paths:
      - "bin/*"

jobs:
  lint:
    permissions:
      contents: read
    name: shellcheck & shfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - uses: luizm/action-sh-checker@17bd25a6ee188d2b91f677060038f4ba37ba14b2 # v0.9.0
    env:
      SHELLCHECK_OPTS: --external-sources
      SHFMT_OPTS: -d -i 2 -ci
